version: '3'
services:
  database:
    # Don't upgrade PostgreSQL by simply changing the version number
    # You need to migrate the Database to the new PostgreSQL version
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      backend:
    restart: always

  # app:
  #   # Uncomment the following section to build the image yourself:
  #   #build:
  #   #  context: .
  #   #  dockerfile: debian/Dockerfile
  #   #  args:
  #   #    - "VERSION=master"
  #   #    - "CODIMD_REPOSITORY=https://github.com/hackmdio/codimd.git"
  #   image: hackmdio/hackmd:1.2.1
  #   environment:
  #     - CMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     backend:
  #   restart: always
  #   depends_on:
  #     - database

# Define networks to allow best isolation
networks:
  # Internal network for communication with PostgreSQL/MySQL
  backend:

# Define named volumes so data stays in place
volumes:
  # Volume for PostgreSQL/MySQL database
  database:
